  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7BC2F932C136453BA93567E5F0F3D7A4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0868980A9A0743339FCCF23784A303DB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_91900B1A77404B80A516F22C662E124A }}

      # ✅ Add this delay step to avoid SCM restart conflict
      - name: Wait before deployment to avoid SCM restart conflict
        run: sleep 60

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Group8CL-webapp'
          slot-name: 'Production'
